export enum AuthResourceEnum {
  ACTION_LOGIN_TEXT = 'Zaloguj się',
  ACTION_REGISTER_TEXT = 'Utwórz konto',
  FIELD_SLUG_LABEL = 'Nazwa powiązana',
  FIELD_SLUG_DESCRIPTION_TEXT = 'Nazwa ta służy jedynie do identyfikacji konta użytkownika w serwisie i nie jest w żaden sposób publicznie powiązana z postaciami użytkownika',
  FIELD_EMAIL_LABEL = 'Adres email',
  FIELD_EMAIL_DESCRIPTION_TEXT = 'Poprawny adres email, który służy za logowanie do serwisu oraz resetowanie hasła',
  FIELD_PASSWORD_LABEL = 'Hasło',
  FIELD_PASSWORD_DESCRIPTION_TEXT = 'Hasło powinno zawierać minimum 10 znaków',
  FIELD_REPEAT_PASSWORD_LABEL = 'Powtórz hasło',
  FIELD_REMEMBER_ME_LABEL = 'Zapamiętaj mnie',
  FIELD_REMEMBER_ME_DESCRIPTION_TEXT = 'Wydłuż sesje użytkownika w przeglądarce do dwóch tygodni zamiast standardowych dwóch dni',
  LOGIN_ISSUES_TEXT = 'Nie możesz się zalogować? ',
  LOGIN_ISSUES_LINK_TEXT = 'Problemy z logowaniem',
  MODAL_LOGIN_TITLE_TEXT = 'Logowanie',
  MODAL_REGISTER_TITLE_TEXT = 'Rejestracja',
  REGISTER_RULES_AGREEMENT_TEXT = 'Tworząc konto akceptujesz tym samym ',
  REGISTER_RULES_AGREEMENT_LINK_TEXT = 'regulamin korzystania z serwisu',
}
