export enum UserResourceEnum {
  MENU_LOGIN_TITLE_TEXT = 'Logowanie',
  MENU_LOGIN_DESCRIPTION_TEXT = 'Zaloguj się na konto by kontynuować rozgrywkę',
  MENU_REGISTER_TITLE_TEXT = 'Rejestracja',
  MENU_REGISTER_DESCRIPTION_TEXT = 'Załóż konto i rozpocznij przygodę w świecie magii',
  MENU_SETTINGS_TITLE_TEXT = 'Edytuj dane',
  MENU_SETTINGS_DESCRIPTION_TEXT = 'zmień swoje hasło oraz adres email, z których korzystasz przy logowaniu',
  MENU_LOGOUT_TITLE_TEXT = 'Wyloguj się',
  MENU_LOGOUT_DESCRIPTION_TEXT = 'Zakończ przygodę do czasu następnego logowania',
  MENU_GUEST_TITLE = 'Menu gościa',
  MENU_USER_TITLE = 'Menu użytkownika',
  MODAL_SETTINGS_CHANGE_EMAIL_TAB_TEXT = 'Zmiana adresu email',
  MODAL_SETTINGS_CHANGE_PASSWORD_TAB_TEXT = 'Zmiana hasła',
  MODAL_SETTINGS_INFORMATION_TAB_TEXT = 'Informacje o koncie',
  FIELD_CURRENT_EMAIL_LABEL = 'Obecny adres email',
  FIELD_NEW_EMAIL_LABEL = 'Nowy adres email',
}
