export enum UserResourceEnum {
  MENU_LOGIN_TITLE_TEXT = 'Logowanie',
  MENU_LOGIN_DESCRIPTION_TEXT = 'Zaloguj się na konto by kontynuować rozgrywkę',
  MENU_REGISTER_TITLE_TEXT = 'Rejestracja',
  MENU_REGISTER_DESCRIPTION_TEXT = 'Załóż konto i rozpocznij przygodę w świecie magii',
  MENU_SETTINGS_TITLE_TEXT = 'Edytuj dane',
  MENU_SETTINGS_DESCRIPTION_TEXT = 'zmień swoje hasło oraz adres email, z których korzystasz przy logowaniu',
  MENU_LOGOUT_TITLE_TEXT = 'Wyloguj się',
  MENU_LOGOUT_DESCRIPTION_TEXT = 'Zakończ przygodę do czasu następnego logowania',
  MENU_GUEST_TITLE = 'Menu gościa',
  MENU_USER_TITLE = 'Menu użytkownika',
  MODAL_SETTINGS_CHANGE_EMAIL_TAB_TEXT = 'Zmiana adresu email',
  MODAL_SETTINGS_CHANGE_PASSWORD_TAB_TEXT = 'Zmiana hasła',
  MODAL_SETTINGS_INFORMATION_TAB_TEXT = 'Informacje o koncie',
  MODAL_SETTINGS_CHANGE_EMAIL_NOTE_TEXT = 'Po zmianie adresu email, użytkownik zostanie wylogowany z aplikacji',
  MODAL_SETTINGS_CHANGE_PASSWORD_NOTE_TEXT = 'Po zmianie hasła, użytkownik zostanie wylogowany z aplikacji',
  MODAL_SETTINGS_INFO_REGISTER_DATE_TEXT = 'Data rejestracji: ',
  MODAL_SETTINGS_INFO_UPDATE_DATE_TEXT = 'Data ostatniej aktualizacji: ',
  MODAL_SETTINGS_INFO_ACTIVE_BLOCK_TEXT = 'Czy konto użytkownika posiada blokadę aktywacyjną: ',
  MODAL_SETTINGS_INFO_USER_GROUP_TEXT = 'Grupa: ',
  MODAL_SETTINGS_INFO_GAME_MASTER_PANEL_TEXT = 'Czy użytkownik ma dostęp do panelu MG: ',
  MODAL_SETTINGS_INFO_CREATE_NEW_CHARACTERS_TEXT = 'Czy użytkownik może tworzyć nowe postacie: ',
  FIELD_CURRENT_EMAIL_LABEL = 'Obecny adres email',
  FIELD_NEW_EMAIL_LABEL = 'Nowy adres email',
  FIELD_CURRENT_PASSWORD_LABEL = 'Obecne hasło',
  FIELD_NEW_PASSWORD_LABEL = 'Nowe hasło',
}
