import { Poppins } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'

const poppins = Poppins({ weight: '300', subsets: ['latin-ext'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>{'Create Next App'}</title>
        <meta name={'description'} content={'Generated by create next app'} />
        <meta name={'viewport'} content={'width=device-width, initial-scale=1'} />
        <link rel={'icon'} href={'/favicon.ico'} />
      </Head>
      <main>
        <span>{'Index'}</span>
      </main>
    </>
  )
}
