import { useState } from 'react'
import { Poppins } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import { AppLogo, TopBar } from '@common'

const poppins = Poppins({ weight: '300', subsets: ['latin-ext'] })

export default function Home() {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <>
      <Head>
        <title>{'Create Next App'}</title>
        <meta name={'description'} content={'Generated by create next app'} />
        <meta name={'viewport'} content={'width=device-width, initial-scale=1'} />
        <link rel={'icon'} href={'/favicon.ico'} />
      </Head>
      <main>
        <TopBar logo={<AppLogo />} setIsOpen={setIsOpen} isOpen={isOpen} />
        <div>
          <p>
            {'Get started by editing'}&nbsp;
            <code>{'src/pages/index.tsx'}</code>
          </p>
          <div>
            <a
              href={
                'https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              }
              target={'_blank'}
              rel={'noopener noreferrer'}
            >
              {'By'} <Image src={'/vercel.svg'} alt={'Vercel Logo'} width={100} height={24} priority />
            </a>
          </div>
        </div>

        <div>
          <Image src={'/next.svg'} alt={'Next.js Logo'} width={180} height={37} priority />
          <div>
            <Image src={'/thirteen.svg'} alt={'13'} width={40} height={31} priority />
          </div>
        </div>

        <div>
          <a
            href={
              'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            }
            target={'_blank'}
            rel={'noopener noreferrer'}
          >
            <h2 className={poppins.className}>
              {'Docs '}
              <span>{'-&gt;'}</span>
            </h2>
            <p className={poppins.className}>{'Find in-depth information about Next.js features and&nbsp;API.'}</p>
          </a>

          <a
            href={
              'https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            }
            target={'_blank'}
            rel={'noopener noreferrer'}
          >
            <h2 className={poppins.className}>
              {'Learn '}
              <span>{'-&gt;'}</span>
            </h2>
            <p className={poppins.className}>{'Learn about Next.js in an interactive course with&nbsp;quizzes!'}</p>
          </a>

          <a
            href={
              'https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            }
            target={'_blank'}
            rel={'noopener noreferrer'}
          >
            <h2 className={poppins.className}>
              {'Templates '}
              <span>{'-&gt;'}</span>
            </h2>
            <p className={poppins.className}>{'Discover and deploy boilerplate example Next.js&nbsp;projects.'}</p>
          </a>

          <a
            href={
              'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            }
            target={'_blank'}
            rel={'noopener noreferrer'}
          >
            <h2 className={poppins.className}>
              {'Deploy '}
              <span>{'-&gt;'}</span>
            </h2>
            <p className={poppins.className}>
              {'Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.'}
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
