export enum ApiKeysEnum {
  GET_MAGIC = 'GET_MAGIC',
  ADD_MAGIC = 'ADD_MAGIC',
  EDIT_MAGIC = 'EDIT_MAGIC',
  DELETE_MAGIC = 'DELETE_MAGIC',
  APPROVE_MAGIC = 'APPROVE_MAGIC',
  CANCEL_MAGIC = 'CANCEL_MAGIC',
}
